### PR TITLE
PMM-9081-create-copyToClipboard-component: change CopyToClipboard wit…

### PR DESCRIPTION
**Pull request by solovevayaroslavna**
**What this PR does / why we need it**:
This PR changing CopyToClipboard from grafanaUi to CopyToclipboard from percona/platform-core for allowing QA to test this component in grafana. 

**Which issue(s) this PR fixes**:
https://jira.percona.com/browse/PMM-9081
image

### CODE REVIEW

**Review by tiagomotasantos — CHANGES_REQUESTED** [review]
Can we get some margin between the button and the rest? Other than that looks good

**Comment by solovevayaroslavna** [comment]
@tiagomotasantos I think yes, but the previous button was without margin. I thought it was done on purpose so that the form and the button represent a single whole.

**Comment by tiagomotasantos** [comment]
I know it was. I don't think it looks good this way, what do you think?

**Comment by solovevayaroslavna** [comment]
When this button is separated from the component, it seems to me that it is a separate part of the form and it is not entirely clear what it is for. But It's only my opinion, we can wait Alex)

**Comment by tiagomotasantos** [comment]
@solovevayaroslavna what form? I only see the copy to clipboard button and the content to be copied.
@atymchuk what's your opinion on this?

**Comment by solovevayaroslavna** [comment]
I meant a <pre> tag, when I talked about form, I'm sorry, <pre> tag looks like a <textArea>, so I made a mistake with the choice of the word. I meant that " it seems to me that it is a separate part of the content area"

**Comment by atymchuk** [comment]
When I look at the screenshot above, it look more appropriate to use Grafana's CopyToClipboard button with text. The use case for the one that you delivered @solovevayaroslavna is when it's part of a label or a description or a header. Other than that we'll use the other one.

**Pull request closed without merging**
