### PR TITLE
PMM-8265 fix typo in Utilisation

### PR DESCRIPTION
**Pull request by solovevayaroslavna**
What this PR does / why we need it:
fix typo in grafana menu Utilisation -> Utilization
image
Which issue(s) this PR fixes: 
https://jira.percona.com/browse/PMM-8265

### CODE REVIEW

**Review by fabio-silva — APPROVED** [review]
Thanks and cheers for the first PR 😄
Just a tip: we usually go with the template that you see when opening a PR, namely these two lines that are already there:
`What this PR does / why we need it: <reason>`
`Which issue(s) this PR fixes: <link_to_jira_ticket>`

If you check other PRs in this repo, you can get an idea 😄

**Comment by solovevayaroslavna** [comment]
@fabio-silva, thanks for the hint, I corrected the description

**Review by tiagomotasantos — APPROVED** [review]
Well done 👍

**Review by atymchuk — APPROVED** [review]
Woohoo! Congrats on your first PR :)

**Pull request merged**
