### PR TITLE
PMM-11771-move-core-ui-to-grafana

### PR DESCRIPTION
**Pull request by filipmikes1**
**What this PR does / why we need it**:
https://jira.percona.com/browse/PMM-11771

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I merged all core-ui components into shared/components/elements. As a result, all components are now only in the shared/elements folder. I merged together only components that were possible to merge. If components were too different, I kept both of them and renamed one from core-ui to [element]Core name. This will make it easier for someone who has a task related to this component to merge it and test if everything is working as before. It will also be easier for testers to test it. I also merged table instances together, so now we have one in shared/components/elements/Table. This table includes all changes from the integrated-alerting table, as well as from the core-ui table.

### CODE REVIEW

**Comment by filipmikes1** [comment]
Special notes for your reviewer:
I merged all core-ui components into shared/components/elements. As a result, all components are now only in the shared/elements folder. I merged together only components that were possible to merge. If components were too different, I kept both of them and renamed one from core-ui to [element]Core name. This will make it easier for someone who has a task related to this component to merge it and test if everything is working as before. It will also be easier for testers to test it. I also merged table instances together, so now we have one in shared/components/elements/Table. This table includes all changes from the integrated-alerting table, as well as from the core-ui table.

**Comment by fabio-silva** [comment]
@filipmikes1 let's fix the conflicts, please

**Comment by filipmikes1** [comment]
> @filipmikes1 let's fix the conflicts, please

Conflicts fixed

**Comment by fabio-silva** [comment]
@filipmikes1 ☝️

**Review by fabio-silva — APPROVED** [review]

**Review by fabio-silva — APPROVED** [review]

**Pull request merged**
